apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: REACT_APP_Google_CLIENT_ID
              value: 258758556440-fc39tl8mv0eihvj1hvc8amltehppehn4.apps.googleusercontent.com
            - name: REACT_APP_Google_Redirect_URL
              value: http://frontend:30210/api/OAuth/Google/Callback
            - name: REACT_APP_Google_ResponseType
              value: code
            - name: REACT_APP_Google_Scope
              value: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
            - name: REACT_APP_SPOTIFY_API
              value: http://localhost:30087/
            - name: REACT_APP_SPOTIFY_API_FILES
              value: http://localhost:30080/
            - name: REACT_APP_SPOTIFY_UI
              value: http://frontend:3000
          image: karantuligor/russian-spotify-frontend
          name: russianspotify-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
      restartPolicy: Always
